version: '3.8'

services:
  frontend:
    image: ghcr.io/takshalmodi02/frontend:latest
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_BACKEND_BASE_URL=${BACKEND_BASE_URL}
    env_file:
      - .env

  backend:
    image: ghcr.io/takshalmodi02/backend:latest
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    ports:
      - "5000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
