name: Build and Push Backend Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      USERNAME: takshalmodi02 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ env.USERNAME }} --password-stdin

      - name: Build the Docker image
        run: docker build -t ghcr.io/${{ env.USERNAME }}/backend:latest .
        working-directory: ./backend

      - name: Push the Docker image
        run: docker push ghcr.io/${{ env.USERNAME }}/backend:latest